name: Run main.py at 5 AM and 5 PM IST

on:
  schedule:
    - cron: "30 23 * * *"   # 5:00 AM IST (11:30 PM UTC previous day)
    - cron: "30 11 * * *"   # 5:00 PM IST (11:30 AM UTC)
  workflow_dispatch:          # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run main.py
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python main.py
